apiVersion: v1
kind: Service
metadata:
  name: {{ include "xemu.fullname" . }}
  labels:
    {{- include "xemu.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "xemu.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
    {{- if .Values.streaming.enabled }}
    - name: broker
      port: {{ .Values.streaming.brokerPort }}
      targetPort: broker
      protocol: TCP
    {{- end }}
