blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/HenriqZimer/xemu-helm-chart/discussions
    about: For questions, use GitHub Discussions
  - name: xemu Docker Image Issues
    url: https://github.com/linuxserver/docker-xemu/issues
    about: For issues with the linuxserver.io xemu image itself (not the Helm chart), use the official image repository
